accounts/urls.py
from django.urls import path
from . import views



app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_view , name='login_view'),
    path('register/', views.register_view , name='register_view'),
    path('logout/', views.logout , name='logout'),
    path('dashboard/', views.dashboard , name='dashboard'),
]

contact/urls.py
from django.urls import path
from . import views


app_name = 'contact'

urlpatterns = [
    path('contact/', views.contact , name='contact'),

]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index , name='index'),
]

futuretrade/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views
from core import views
from contact import views
from pages import views

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
    path('contact/', include('contact.urls')),
    path('pages/', include('pages.urls')),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


admin.site.site_header ="Future Trade Option control panel"
admin.site.index_title ="Administrators dashboard"
admin.site.site_title ="Control panel"

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('about/', views.about , name='about'),
    path('services/', views.services , name='services'),
]

accounts/models.py
from django.db import models
from datetime import datetime
from django.utils.timezone import timezone

from django.contrib.auth.models import User

# Create your models here.

class Trade(models.Model):
	title = models.CharField(max_length=200)
	user = models.ForeignKey(User , on_delete=models.DO_NOTHING, blank=True)
	trading_ammount = models.IntegerField()
	profit = models.IntegerField()
	intrestrate = models.IntegerField()
	is_published = models.BooleanField(default=True)
	list_date = models.DateTimeField(default=datetime.now , blank=True)


	def __str__(self):
		return self.title;

contact/models.py
from django.db import models
from datetime import datetime
# Create your models here.
class Contact(models.Model):
	name = models.CharField(max_length=200)
	email = models.CharField(max_length=100)
	phone = models.CharField(max_length=100)
	message = models.TextField(blank=True)
	contact_date = models.DateTimeField(default=datetime.now() , blank=True)
	user_id = models.IntegerField(blank=True)

	def __str__(self):
		return self.name

core/models.py
from django.db import models

# Create your models here.

pages/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render,redirect,get_object_or_404
from django.http import HttpResponse
from django.contrib import messages,auth
from django.contrib.auth.models import User
from contact.models import Contact
from . models import Trade


# Create your views here.
def register_view(request):
	if request.method == 'POST':
		first_name = request.POST['first_name']
		last_name = request.POST['last_name']
		username = request.POST['username']
		email = request.POST['email']
		password = request.POST['password']
		password2 = request.POST['password2']

		if password == password2:
			if User.objects.filter(username=username).exists():
					messages.error(request , 'User Name Already Taken')
					return redirect('accounts:register_view')
			else:
				if User.objects.filter(email=email).exists():
					messages.error(request , 'Email Name Already Exits ')
					return redirect('accounts:register_view')
				else:
					user = User.objects.create_user(username=username,password=password,email=email,first_name=first_name,last_name
						=last_name)
					# auth.login(request , user)
					# messages.success(request,'You Are Now LoggedIn')
					# return redirect('pages:index')
					user.save()
					messages.success(request,'You Are Now Registered')
					return redirect('accounts:login_view')
		else:
			messages.error(request , 'Password Doest Not Match')
			return redirect('accounts:register_view')

	else:
		return render(request,'account/register.html')


def login_view(request):
	if request.method == 'POST':
		username = request.POST['username']
		password = request.POST['password']

		user = auth.authenticate(username=username , password=password)
		if user is not None:
			auth.login(request,user)
			messages.success(request,'You Are Now LoggedIn')
			return redirect('accounts:dashboard')
		else:
			messages.error(request,'Invalid Credentials')
			return redirect('accounts:login_view')
	else:
		return render(request,'account/signin.html')

def logout(request):
	auth.logout(request)
	if request.method == 'POST':
		auth.logout(request)
		messages.success(request,'You Are Now Logged Out')
		return render(request,'core/index.html')
	return redirect('accounts:login_view')

def dashboard(request):
	trades = Trade.objects.filter(user=request.user.id)
	return render(request,'core/dashboard.html', {'trades' : trades})

contact/views.py
from django.shortcuts import render,redirect
from django.contrib import messages

from .models import Contact

# Create your views here.
def contact(request):
	if request.method == 'POST':
		name = request.POST['name']
		email = request.POST['email']
		phone = request.POST['phone']
		message = request.POST['message']
		user_id = request.POST['user_id']

		contact = Contact(name=name,email=email,phone=phone, message=message,user_id = user_id)
		contact.save()
		
		messages.success(request,'Your Request has Been Submitted')
		return render(request , 'contact/contact.html')

	else:
		return render(request,'contact/contact.html')

core/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render,redirect

# Create your views here.
def index(request):
	return render(request , 'core/index.html')

pages/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render,redirect

# Create your views here.

def about(request):
	return render(request , 'core/about.html')


def services(request):
	return render(request , 'core/services.html')

templates/Snippets/alert.html
{% if messages %}
    {% for message in messages %}
       <div class="container" id="message">
       	 <div class="alert alert-{{ message.tags }} alert-dismissable text-center" role="alert">
       	 	<button type="button" data-dismiss="alert" class="close"><span aria-hidden=true>
       	 		&times;
       	 	</span></button>
       	 	<strong>
       	 		{% if  message.level == DEFAULT_MESSAGE_LEVELS.ERROR%}
       	 		    Error:
       	 		{% else %}
       	 		     {{ message.tags|title }}
       	 		{% endif %}
       	 	</strong>
       	 	{{ message }}
       	 </div>
       </div>
    {% endfor %}
{% endif %}

templates/Snippets/footer.html
{% load static %}
<footer>
    <!--? Footer Start-->
    <div class="footer-area section-bg" data-background="  {%static './assets/img/gallery/footer_bg.jpg'%}">
        <div class="container">
            <div class="footer-top footer-padding">
                <div class="row d-flex justify-content-between">
                    <div class="col-xl-3 col-lg-4 col-md-5 col-sm-8">
                        <div class="single-footer-caption mb-50">
                            <!-- logo -->
                            <div class="footer-logo">
                                <a href="index.html"><img src=" {%static './assets/img/logo/logo2_footer.png'%}" alt=""></a>
                            </div>
                            <div class="footer-tittle">
                                <div class="footer-pera">
                                    <p class="info1">Receive updates and latest news direct from Simply enter.</p>
                                </div>
                            </div>
                            <div class="footer-number">
                                <h4><span>+564 </span>7885 3222</h4>
                                <p>support@futuretradeoption.com</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-2 col-lg-2 col-md-3 col-sm-5">
                        <div class="single-footer-caption mb-50">
                            <div class="footer-tittle">
                                <h4>Location </h4>
                                <ul>
                                    <li><a href="#">Advanced</a></li>
                                    <li><a href="#"> Management</a></li>
                                    <li><a href="#">Corporate</a></li>
                                    <li><a href="#">Customer</a></li>
                                    <li><a href="#">Information</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-2 col-lg-2 col-md-3 col-sm-5">
                        <div class="single-footer-caption mb-50">
                            <div class="footer-tittle">
                                <h4>Explore</h4>
                                <ul>
                                    <li><a href="#">Cookies</a></li>
                                    <li><a href="#">About</a></li>
                                    <li><a href="#">Privacy Policy</a></li>
                                    <li><a href="#">Proparties</a></li>
                                    <li><a href="#">Licenses</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-4 col-lg-4 col-md-6 col-sm-8">
                        <div class="single-footer-caption mb-50">
                            <div class="footer-tittle">
                                <h4>Location</h4>
                                <div class="footer-pera">
                                    <p class="info1">Subscribe now to get daily updates</p>
                                </div>
                            </div>
                            <!-- Form -->
                            <div class="footer-form">
                                <div id="mc_embed_signup">
                                    <form target="_blank" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01" method="get" class="subscribe_form relative mail_part" novalidate="true">
                                        <input type="email" name="EMAIL" id="newsletter-form-email" placeholder=" Email Address " class="placeholder hide-on-focus" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Your email address'">
                                        <div class="form-icon">
                                            <button type="submit" name="submit" id="newsletter-submit" class="email_icon newsletter-submit button-contactForm">
                                                SIGN UP
                                            </button>
                                        </div>
                                        <div class="mt-10 info"></div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="footer-bottom">
                <div class="row d-flex justify-content-between align-items-center">
                    <div class="col-xl-9 col-lg-8">
                        <div class="footer-copy-right">
                            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | Future Trade Option</a>
  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-4">
                        <!-- Footer Social -->
                        <div class="footer-social f-right">
                            <a href="#"><i class="fab fa-twitter"></i></a>
                            <a href="https://www.facebook.com/sai4ull"><i class="fab fa-facebook-f"></i></a>
                            <a href="#"><i class="fas fa-globe"></i></a>
                            <a href="#"><i class="fab fa-instagram"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer End-->
</footer>

templates/Snippets/header.html
{% load static %}
<header>
    <!-- Header Start -->
    <div class="header-area">
        <div class="main-header ">
            <div class="header-top d-none d-lg-block">
                <div class="container">
                    <div class="col-xl-12">
                        <div class="row d-flex justify-content-between align-items-center">
                            <div class="header-info-left">
                                <ul>     
                                    <li><i class="far fa-clock"></i> Mon - Fri: 08.00 am - 06.00 pm</li>
                                    <li>Sat & Sun:  Closed</li>
                                </ul>
                            </div>
                            <div class="header-info-right">
                                <ul class="header-social">    
                                    <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                                    <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                                    <li><a href="#"><i class="fab fa-linkedin-in"></i></a></li>
                                    <li> <a href="#"><i class="fab fa-google-plus-g"></i></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="header-bottom  header-sticky">
                <div class="container">
                    <div class="row align-items-center">
                        <!-- Logo -->
                        <div class="col-xl-2 col-lg-2">
                            <div class="logo">
                                <a href="index.html"><img src=" {%static './assets/img/logo/logo.png'%}" alt=""></a>
                            </div>
                        </div>
                        <div class="col-xl-10 col-lg-10">
                            <div class="menu-wrapper  d-flex align-items-center justify-content-end">
                                <!-- Main-menu -->
                                <div class="main-menu d-none d-lg-block">
                                    <nav> 
                                        <ul id="navigation">                                                                                          
                                            <li><a href="{% url 'core:index' %}">Home</a></li>
                                            <li><a href="{% url 'pages:about' %}">About</a></li>
                                            <li><a href="{% url 'pages:services' %}">Services</a></li>
                                            <li><a href="#">Account</a>
                                                <ul class="submenu">
                                                	{% if user.is_authenticated %}
                                                    <li><a href="{% url 'accounts:dashboard' %}">Dashboard</a></li>
                                                     <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                                                     {% else %}
                                                    <li><a href="{% url 'accounts:register_view' %}">Register</a></li>
                                                    <li><a href="{% url 'accounts:login_view' %}">Login</a></li>
                                                    {% endif %}

                                                </ul>
                                            </li>
                                            <li><a href="{% url 'contact:contact' %}">Contact</a></li>
                                        </ul>
                                    </nav>
                                </div>
                            </div>
                        </div> 
                        <!-- Mobile Menu -->
                        <div class="col-12">
                            <div class="mobile_menu d-block d-lg-none"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
 <div class="tradingview-widget-container">
  <script type="text/javascript" src="https://s3.tradingview.com/external-embedding/embed-widget-ticker-tape.js" async>
  {
  "symbols": [
    {
      "proName": "FOREXCOM:SPXUSD",
      "title": "S&P 500"
    },
    {
      "proName": "FOREXCOM:NSXUSD",
      "title": "Nasdaq 100"
    },
    {
      "proName": "FX_IDC:EURUSD",
      "title": "EUR/USD"
    },
    {
      "proName": "BITSTAMP:BTCUSD",
      "title": "BTC/USD"
    },
    {
      "proName": "BITSTAMP:ETHUSD",
      "title": "ETH/USD"
    }
  ],
  "showSymbolLogo": true,
  "colorTheme": "dark",
  "isTransparent": false,
  "displayMode": "adaptive",
  "locale": "en"
}
  </script>
</div>
</div>
    <!-- Header End -->
</header>
<!-- TradingView Widget BEGIN -->

<!-- TradingView Widget END -->

templates/base.html
{% load static %}
<!doctype html>
<html class="no-js" lang="zxx">
<head>
	<meta charset="utf-8">
	<meta http-equiv="x-ua-compatible" content="ie=edge">
	<title>{% block title %}
{% endblock title %} </title>
	<meta name="description" content="">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="manifest" href="site.webmanifest">
	<link rel="shortcut icon" type="image/x-icon" href="{%static './assets/img/favicon.ico'%}">

	<!-- CSS here -->
	<link rel="stylesheet" href="{% static './assets/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static './assets/css/owl.carousel.min.css' %}">
	<link rel="stylesheet" href="{% static './assets/css/slicknav.css' %}">
	<link rel="stylesheet" href="{% static './assets/css/flaticon.css' %}">
	<link rel="stylesheet" href="{% static './assets/css/animate.min.css' %}">
	<link rel="stylesheet" href="{% static './assets/css/magnific-popup.css' %}">
	<link rel="stylesheet" href="{% static './assets/css/fontawesome-all.min.css' %}">
	<link rel="stylesheet" href="{% static './assets/css/themify-icons.css' %}">
	<link rel="stylesheet" href="{% static './assets/css/slick.css' %}">
	<link rel="stylesheet" href="{% static './assets/css/nice-select.css' %}">
	<link rel="stylesheet" href="{% static './assets/css/style.css' %}">
</head>

<body class="body-bg">
<!--? Preloader Start -->
<div id="preloader-active">
    <div class="preloader d-flex align-items-center justify-content-center">
        <div class="preloader-inner position-relative">
            <div class="preloader-circle"></div>
            <div class="preloader-img pere-text">
                <img src="{%static './assets/img/logo/loder.png'%}" alt="">
            </div>
        </div>
    </div>
</div>

 {% include 'Snippets/header.html' %}
  
 {% block header %}


  {% endblock header%}

  {% block content %}


  {% endblock content %}
{% include 'Snippets/footer.html' %}

<!-- Scroll Up -->
<div id="back-top" >
    <a title="Go to Top" href="#"> <i class="fas fa-level-up-alt"></i></a>
</div>

    <!-- JS here -->

    <script src="{% static './assets/js/vendor/modernizr-3.5.0.min.js' %}"></script>
    <!-- Jquery, Popper, Bootstrap -->
    <script src="{% static './assets/js/vendor/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static './assets/js/popper.min.js' %}"></script>
    <script src="{% static './assets/js/bootstrap.min.js' %}"></script>
    <!-- Jquery Mobile Menu -->
    <script src="{% static './assets/js/jquery.slicknav.min.js' %}"></script>

    <!-- Jquery Slick , Owl-Carousel Plugins -->
    <script src="{% static './assets/js/owl.carousel.min.js' %}"></script>
    <script src="{% static './assets/js/slick.min.js' %}"></script>
    <!-- One Page, Animated-HeadLin -->
    <script src="{% static './assets/js/wow.min.js' %}"></script>
    <script src="{% static './assets/js/animated.headline.js' %}"></script>
    <script src="{% static './assets/js/jquery.magnific-popup.js' %}"></script>

    <!-- Nice-select, sticky -->
    <script src="{% static './assets/js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static './assets/js/jquery.sticky.js' %}"></script>

    <!-- counter , waypoint -->
    <script src="http://cdnjs.cloudflare.com/ajax/libs/waypoints/2.0.3/waypoints.min.js"></script>
    <script src="{% static './assets/js/jquery.counterup.min.js' %}"></script>
    
    <!-- contact js -->
    <script src="{% static './assets/js/contact.js' %}"></script>
    <script src="{% static './assets/js/jquery.form.js' %}"></script>
    <script src="{% static './assets/js/jquery.validate.min.js' %}"></script>
    <script src="{% static './assets/js/mail-script.js' %}"></script>
    <script src="{% static './assets/js/jquery.ajaxchimp.min.js' %}"></script>
    
    <!-- Jquery Plugins, main Jquery -->	
    <script src="{% static './assets/js/plugins.js' %}"></script>
    <script src="{% static './assets/js/main.js' %}"></script>
        
    </body>
</html>

templates/core/about.html
{% extends "base.html" %}

{% load static %}

{% block title %}
     Future Option Trade-About
{% endblock title %}

{% block content %}

    <main>
        <!--? Hero Start -->
        <div class="slider-area2">
            <div class="slider-height2 hero-overly2 d-flex align-items-center">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-12">
                            <div class="hero-cap hero-cap2 text-center">
                                <h2>About Us</h2>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Hero End -->
        <div class="about-details section-padding30">
            <div class="container">
                <div class="row">
                    <div class="offset-xl-1 col-lg-8">
                        <div class="about-details-cap mb-50">
                            <h4>Our Mission</h4>
                            <p>Your wealth is more than a sum of investments. It can be a powerful tool for improving the world around you. We help our clients crystallize and prioritize the environmental and social issues they care about most and develop a plan that allows their wealth to positively influence them. We call this intersection between your financial and non-financial objectives sustainable investing.
                             </p>
                             <p> The belief that wealth can simultaneously achieve both desired financial outcomes and positive societal change is deeply embedded in our culture. The Laird and Norton families who founded our firm were pioneers in sustainable investing, who now steer nearly 100% of their family foundation’s investments toward impact-related funds and projects. We apply the successes and lessons they learned along the way to our clients’ own sustainable investment aspirations. </p>
                        </div>

                        <div class="about-details-cap mb-50">
                            <h4>Our Vision</h4>
                            <p>At Laird Norton Wealth Management, we are advocates and stewards for your life, your wealth and your legacy. Our integrated approach brings together the brightest minds in each aspect of wealth management: financial and tax planning; investment management; trust and estate planning.
                             </p>
                             <p>  Your advisory team is here to serve you in all aspects of your financial life – from cash flow planning to serving as your trustee. Knowing you is key to the success of your plan.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--? About Area Start-->
        <div class="support-company-area pt-100 pb-100 section-bg fix" data-background="{%static './assets/img/gallery/section_bg02.jpg'%}">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-xl-6 col-lg-6">
                        <div class="support-location-img">
                            <img src="{%static './assets/img/gallery/about.png'%}" alt="">
                        </div>
                    </div>
                   <div class="col-xl-6 col-lg-6">
                    <div class="right-caption">
                        <!-- Section Tittle -->
                        <div class="section-tittle section-tittle2 mb-50">
                            <span>Our Top Services</span>
                            <h2>Our Best Services</h2>
                        </div>
                        <div class="support-caption">
                            <p class="pera-top">Envision a more complete strategy for your life and wealth. From your immediate needs, to your lifetime goals, and the legacy you leave, how you think about your wealth touches every part of your life. We can help you see your big picture and set your course, with expertise in wealth planning, investment management, trust services, and more. </p>
                            <p class="mb-65">Each aspect of wealth management we provide is essential in helping you realize your vision of family, of community, and of your world. We can help you simplify, clarify, and bring your ideals to life. We call this Wealth Regeneration®—a more human, more integrated take on your financial life. Find out more about How We Help..</p>
                            <a href="about.html" class="btn post-btn">More About Us</a>
                        </div>
                    </div>
                </div>

                </div>
            </div>
        </div>
        <!-- About Area End-->
        <!-- Team Start -->
        <div class="team-area section-padding30">
            <div class="container">
                <div class="row">
                    <div class="cl-xl-7 col-lg-8 col-md-10">
                        <!-- Section Tittle -->
                        <div class="section-tittle mb-70">
                            <span>Our Professional members </span>
                            <h2>Our Team Mambers</h2>
                        </div> 
                    </div>
                </div>
                <div class="row">
                    <!-- single Tem -->
                    <div class="col-xl-4 col-lg-4 col-md-6 col-sm-">
                        <div class="single-team mb-30">
                            <div class="team-img">
                                <img src="{%static './assets/img/gallery/team2.png'%}" alt="">
                            </div>
                            <div class="team-caption">
                                <h3><a href="#">Ethan Welch</a></h3>
                                <span>UX Designer</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-4 col-lg-4 col-md-6 col-sm-">
                        <div class="single-team mb-30">
                            <div class="team-img">
                                <img src="{%static './assets/img/gallery/team3.png'%}" alt="">
                            </div>
                            <div class="team-caption">
                                <h3><a href="#">Ethan Welch</a></h3>
                                <span>UX Designer</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-4 col-lg-4 col-md-6 col-sm-">
                        <div class="single-team mb-30">
                            <div class="team-img">
                                <img src="{%static './assets/img/gallery/team1.png'%}" alt="">
                            </div>
                            <div class="team-caption">
                                <h3><a href="#">Ethan Welch</a></h3>
                                <span>UX Designer</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Team End -->
       
        <!-- Coun Down End -->
        <!-- Brand Area Start -->
        <div class="brand-area pt-150 pb-140">
            <div class="container">
                <div class="brand-active brand-border pb-40">
                    <div class="single-brand">
                        <img src="{%static './assets/img/gallery/brand1.png'%}" alt="">
                    </div>
                    <div class="single-brand">
                        <img src="{%static './assets/img/gallery/brand2.png'%}" alt="">
                    </div>
                    <div class="single-brand">
                        <img src="{%static './assets/img/gallery/brand3.png'%}" alt="">
                    </div>
                    <div class="single-brand">
                        <img src="{%static './assets/img/gallery/brand4.png'%}" alt="">
                    </div>
                    <div class="single-brand">
                        <img src="{%static './assets/img/gallery/brand2.png'%}" alt="">
                    </div>
                    <div class="single-brand">
                        <img src="{%static './assets/img/gallery/brand5.png'%}" alt="">
                    </div>
                </div>
            </div>
        </div>
        <!-- Brand Area End -->
    </main>
 <script src="https://account.snatchbot.me/script.js"></script><script>window.sntchChat.Init(213633)</script> 
{% endblock content %}